server {
    listen 80;
    listen [::]:80;
    server_name geometry.oipav.ru;

    root /var/www/geometry;
    index index.html;

    access_log /var/log/nginx/geometry.access.log;
    error_log /var/log/nginx/geometry.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
